package entity;
// Generated Nov 24, 2019 1:10:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaiKhoan generated by hbm2java
 */
@Entity
@Table(name="TaiKhoan"
    ,schema="dbo"
    ,catalog="dn1"
)
public class TaiKhoan  implements java.io.Serializable {


     private String tenDangNhap;
     private String matKhau;
     private boolean vaiTro;
     private Integer thoiGian;
     private Integer soCau;
     private Integer tien;

    public TaiKhoan() {
    }

	
    public TaiKhoan(String tenDangNhap, String matKhau, boolean vaiTro) {
        this.tenDangNhap = tenDangNhap;
        this.matKhau = matKhau;
        this.vaiTro = vaiTro;
    }
    public TaiKhoan(String tenDangNhap, String matKhau, boolean vaiTro, Integer thoiGian, Integer soCau, Integer tien) {
       this.tenDangNhap = tenDangNhap;
       this.matKhau = matKhau;
       this.vaiTro = vaiTro;
       this.thoiGian = thoiGian;
       this.soCau = soCau;
       this.tien = tien;
    }
   
     @Id 

    
    @Column(name="TenDangNhap", unique=true, nullable=false, length=50)
    public String getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(String tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }

    
    @Column(name="MatKhau", nullable=false, length=50)
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    
    @Column(name="VaiTro", nullable=false)
    public boolean isVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(boolean vaiTro) {
        this.vaiTro = vaiTro;
    }

    
    @Column(name="ThoiGian")
    public Integer getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Integer thoiGian) {
        this.thoiGian = thoiGian;
    }

    
    @Column(name="SoCau")
    public Integer getSoCau() {
        return this.soCau;
    }
    
    public void setSoCau(Integer soCau) {
        this.soCau = soCau;
    }

    
    @Column(name="Tien")
    public Integer getTien() {
        return this.tien;
    }
    
    public void setTien(Integer tien) {
        this.tien = tien;
    }




}


